name: $(Date:yyyyMMdd)$(Rev:rr)
resources:
- repo: self

trigger:
  batch: 'true'
  branches:
    include:
    - master

pool:
  vmImage: 'windows-2019'

steps:

  - task: PowerShell@2
    displayName: 'Run Cake PowerShell Bootstrapper'
    inputs:
      filePath: 'build.ps1'
      arguments: '-Verbosity Diagnostic -Target CI -BuildNumber=$(Build.BuildNumber)'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: PublishTestResults@2
    displayName: 'Publish .NET test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      mergeTestResults: true
      testRunTitle: 'C# Unit Tests'

  - task: PublishCodeCoverageResults@1
    displayName: 'publish .NET coverage results'
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

  - task: CopyFiles@2
    displayName: Copy NuGet package to Artifact Staging Directory
    inputs:
      Contents: artifacts/**
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'publish artifacts'
    inputs:
      ArtifactName: 'drop'
